package collections;

import java.util.HashSet;
import java.util.Set;

public class SetDemo1 {
	public static void main(String[] args) {
		//choosing "set" for if we want to have the unique elements or remove duplicates
		Set<String> hs=new HashSet<String>();
		//hashCode()-->it is used to retrieve memory stored unique code generated by JVM at time of the object
		//System.out.println("FLM".hashCode()%16);
		hs.add("FLM");
		hs.add("Selenium");
		hs.add("Java");
		System.out.println(hs.size());
		System.out.println(hs);
		for(String temp:hs) {
			System.out.println(temp);
		}
		//adding duplicate data
		hs.add("FLM");
		hs.add("Java");
		//set having all methods as same as collection and ArrayList except"get(int)".
//		for(int i=0;i<hs.size();i++) {
//			System.out.println(hs.get(i));//The method get(int) is undefined for the type Set<String>
//		}
		
		
		for(String temp:hs) {
			System.out.println(temp);
		}
		
	}
}