package collections;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

public class SetDemo2UsingIterator {
	public static void main(String[] args) {
		//choosing "set" for if we want to have the unique elements or remove duplicates
		Set<String> hs=new HashSet<String>();
		//hashCode()-->it is used to retrieve memory stored unique code generated by JVM at time of the object
		//System.out.println("FLM".hashCode()%16);
		hs.add("FLM");
		hs.add("Selenium");
		hs.add("Java");
		System.out.println(hs.size());
		System.out.println(hs);
		for(String temp:hs) {
			System.out.println(temp);
		}
		//adding duplicate data
		hs.add("FLM");
		hs.add("Java");
		//iterator method
		Iterator<String> it=hs.iterator();
		//hasNext()-->true if the iteration has element on next level
		//next()-->Returns the next element in the iteration.
		while(it.hasNext()) {
			System.out.println(it.next());
		}
	}
}
